export const FETCH_POKEMONS_REQUEST = 'FETCH_POKEMONS_REQUEST';
export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS';
export const FETCH_POKEMONS_FAILURE = 'FETCH_POKEMONS_FAILURE';

export const SELECT_POKEMON_REQUEST = 'SELECT_POKEMON_REQUEST';
export const SELECT_POKEMON_SUCCESS = 'SELECT_POKEMON_SUCCESS';
export const SELECT_POKEMON_FAILURE = 'SELECT_POKEMON_FAILURE';
